services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meridiano
    ports:
      - "5460:5432"
